name: deprem_destek
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  cloud_firestore: 4.3.1
  collection: 1.16.0

  cupertino_icons: 1.0.2
  firebase_auth: 4.2.5
  firebase_core: 2.4.1
  flutter:
    sdk: flutter
  flutter_bloc: 8.1.1
  freezed_annotation: ^2.2.0
  geoflutterfire2: 2.3.14
  json_annotation: ^4.8.0

dev_dependencies:
  build_runner: 2.3.3
  flutter_lints: 1.0.0
  flutter_test:
    sdk: flutter
  freezed: 2.3.2
  json_serializable: ^6.6.1
  very_good_analysis: 3.1.0

flutter:
  uses-material-design: true
